# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "TwitterStalker::App"

# The default layout to use for your application (located in
# views/layouts/main.tt)
#layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT
#template: "simple"

# Followed instructions here: 
# http://search.cpan.org/~yanick/Dancer-1.3121/lib/Dancer/Template/TemplateToolkit.pm
# but that page left out important info!
# you have to run 'sudo cpan install Template' first
template: "template_toolkit"
engines:
        template_toolkit:
            WRAPPER: layouts/main.tt
            EVAL_PERL: 1
# engines:
#   template_toolkit:
#     start_tag: '[%'
#     end_tag:   '%]'

